name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run typecheck (optional if using TypeScript)
        run: |
          if [ -f tsconfig.json ]; then
            npm run typecheck || true
          fi

      - name: Run tests (optional)
        run: |
          if [ -f package.json ]; then
            npm test || true
          fi

      - name: Build app
        run: npm run build
